default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres             # Usuario para todas las configuraciones
  password: admin                # Contrase침a para desarrollo y pruebas
  host: localhost                # Cambia esto si es necesario

development:
  <<: *default
  database: development_postgresql_market

test:
  <<: *default
  database: test_postgresql_market

production:
  <<: *default
  database: production_postgresql_market
  username: <%= ENV['DATABASE_USERNAME'] %>  # Usuario en producci칩n desde variable de entorno
  password: <%= ENV['DATABASE_PASSWORD'] %>  # Contrase침a en producci칩n desde variable de entorno
